version: "3.8"

services:
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: hotel_backend
  #   environment:
  #     - PORT=5000
  #     - DB_HOST=db
  #     - DB_USER=admin
  #     - DB_PASSWORD=admin
  #     - DB_NAME=hotel_reservation
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./backend:/usr/src/app
  #     - /usr/src/app/node_modules

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hotel_reservation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
